[package]
authors = ["The Nushell Project Developers"]
description = "Support for writing Nushell tests"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-test-support"
edition = "2024"
license = "MIT"
name = "nu-test-support"
version = "0.107.1"

[lib]
doctest = false
bench = false

[lints]
workspace = true

[dependencies]
nu-experimental = { path = "../nu-experimental", version = "0.107.1" }
nu-glob = { path = "../nu-glob", version = "0.107.1" }
nu-path = { path = "../nu-path", version = "0.107.1" }
nu-test-support-macros = { path = "../nu-test-support-macros", version = "0.107.1" }
nu-utils = { path = "../nu-utils", version = "0.107.1" }

itertools = { workspace = true }
libtest-with = { workspace = true }
linkme = { workspace = true }
num-format = { workspace = true }
tempfile = { workspace = true }
which = { workspace = true }
